#!/bin/bash
# ETL Pipeline - Full Configuration for Academic Research

echo "========================================"
echo "ETL Pipeline - Full Configuration"
echo "For Academic Research"
echo "========================================"
echo ""
echo "Creating embeddings for ALL tasks with:"
echo "- Split Strategy: modn (ID mod 200)"
echo "- Sources: desc (title+description) + title (title only)"
echo "- Targets: module + file"
echo "- Window: all (complete history)"
echo "- Model: bge-small"
echo ""
echo "This will create 4 Qdrant collections:"
echo "  1. rag_exp_desc_module_all_modn   (title+desc combined, module)"
echo "  2. rag_exp_desc_file_all_modn     (title+desc combined, file)"
echo "  3. rag_exp_title_module_all_modn  (title only, module)"
echo "  4. rag_exp_title_file_all_modn    (title only, file)"
echo ""
echo "For comparing title-only vs title+description effectiveness"
echo ""
echo "Estimated time with GPU: 12-20 minutes"
echo "Estimated time with CPU: 60-70 minutes"
echo "========================================"
echo ""

python3 etl_pipeline.py --split_strategy modn --sources desc title --targets module file --windows all --model bge-small

echo ""
echo "========================================"
echo "ETL Pipeline completed!"
echo ""
echo "Collections created:"
echo "- rag_exp_desc_module_all_modn"
echo "- rag_exp_desc_file_all_modn"
echo "- rag_exp_title_module_all_modn"
echo "- rag_exp_title_file_all_modn"
echo ""
echo "Next step: Backup collections"
echo "  ./backup_qdrant.sh"
echo "========================================"
