#!/usr/bin/env python3
"""
Roll up per-(project, task_unit) checkpoint state into experiment_results/STATUS.md.

Source of truth is always the checkpoint.json files themselves - this
script just makes them scannable at a glance. Safe/cheap to re-run any
time; see EXPERIMENT_PLAN.md Sec.5 (resume protocol).
"""

import argparse
import glob
import json
import os


def load_checkpoint(path: str) -> dict:
    with open(path) as f:
        return json.load(f)


def collect_rows(results_dir: str) -> list:
    rows = []
    pattern = os.path.join(results_dir, '*', '*', 'checkpoint.json')
    for checkpoint_path in sorted(glob.glob(pattern)):
        parts = checkpoint_path.split(os.sep)
        # .../<results_dir>/<project>/<task_unit>/checkpoint.json
        task_unit = parts[-2]
        project = parts[-3]

        try:
            data = load_checkpoint(checkpoint_path)
        except Exception as e:
            rows.append({
                'project': project, 'task_unit': task_unit,
                'done': 0, 'failed': 0, 'last_updated': '',
                'status': f'ERROR reading checkpoint: {e}'
            })
            continue

        done = len(data.get('completed_experiments', []))
        failed_etl = len(data.get('failed_etl', []))
        failed_exp = len(data.get('failed_experiments', []))
        failed = failed_etl + failed_exp
        last_updated = data.get('last_updated', '')

        if failed > 0:
            status = f'failed: {failed}'
        elif done > 0:
            status = 'in_progress'  # can't know the intended total without re-passing the variant grid
        else:
            status = 'not_started'

        rows.append({
            'project': project, 'task_unit': task_unit,
            'done': done, 'failed': failed,
            'last_updated': last_updated, 'status': status
        })

    return rows


def write_status_md(rows: list, output_file: str):
    lines = [
        '# exp3.1 Experiment Status',
        '',
        '(auto-generated by status.py - source of truth is the checkpoint.json files, not this file)',
        '',
        '| project | task_unit | done | failed | last_updated | status |',
        '|---|---|---|---|---|---|',
    ]
    for r in rows:
        lines.append(
            f"| {r['project']} | {r['task_unit']} | {r['done']} | {r['failed']} | "
            f"{r['last_updated']} | {r['status']} |"
        )
    lines.append('')

    with open(output_file, 'w') as f:
        f.write('\n'.join(lines))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--results-dir', default='experiment_results',
                         help='Root directory containing <project>/<task_unit>/checkpoint.json')
    args = parser.parse_args()

    rows = collect_rows(args.results_dir)
    if not rows:
        print(f"No checkpoint.json files found under {args.results_dir}/*/*/")
        return

    output_file = os.path.join(args.results_dir, 'STATUS.md')
    write_status_md(rows, output_file)

    print(f"Wrote {len(rows)} row(s) to {output_file}")
    for r in rows:
        print(f"  {r['project']}/{r['task_unit']}: done={r['done']} failed={r['failed']} status={r['status']}")


if __name__ == '__main__':
    main()
